name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Deps
        run: yarn install

      - name: Run Tests
        run: yarn run test

      - name: Compile
        run: yarn run prod

      - name: Run Linter
        run: yarn run lint

      - name: Run Type-checking for Tests
        run: yarn run test:typecheck
