name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  main:
    strategy:
      matrix:
        kind: ["linux", "windows", "macOS"]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: mac-x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Deps
        run: yarn install

      - name: Run Linter
        if: matrix.kind == 'linux'
        run: yarn run lint

      - name: Run Tests
        if: matrix.kind == 'linux'
        run: yarn run test

      - name: Compile
        run: yarn run prod
